version: '3'
services:

  frontend:
    entrypoint: "http-server-spa build index.html 3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - internal 
    depends_on:
      - frontend
      - backend
