version: '3'
services:

  frontend:
    build: 
      context: ./frontend
      args: 
        - API_URL
        - HOSTNAME
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    env_file:
      - env
    expose: 
      - "3000"
    stdin_open: true
    networks:
      - internal

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - env
    expose:
      - "5000"
    volumes:
      - ./backend:/app
      - /uploads:/uploads
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: lomb
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: lomb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      FLASK_ENV: development
    volumes:
      - mongodbdata:/data/db
    networks:
      - internal

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    restart: unless-stopped
    ports: 
      - 8888:8888
    networks: 
      - internal
    volumes:
      - jupyternotebooks:/home/jovyan/work

volumes:
  mongodbdata:
  node_modules:
  jupyternotebooks:
networks:
  internal:
