version: '3'
services:
  backend:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: lomb
      MONGODB_USERNAME: lomb
      MONGODB_PASSWORD: secret
      MONGODB_HOSTNAME: mongodb
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: lomb
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: lomb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

volumes:
  mongodbdata:
networks:
  backend:
  frontend:
