TEXT__WORD_HIGHLIGHTED = "TEXT__WORD_HIGHLIGHTED"
TEXT__SENTENCE_CLICK = "TEXT__SENTENCE_CLICK"
TEXT__SENTENCE_READ = "TEXT__SENTENCE_READ"
REVISION__CLICKED = "REVISION__CLICKED"
REVISION__NOT_CLICKED = "REVISION__NOT_CLICKED"
VIDEO__WAS_SEEN = "VIDEO__WAS_SEEN"
VIDEO__TRANSLATION_WAS_REVEALED = "VIDEO__TRANSLATION_WAS_REVEALED"
BOOK_DRILL_SCROLL= "BOOK_DRILL_SCROLL"
BOOK_DRILL_CLICK= "BOOK_DRILL_CLICK"

valid_messages = [
    TEXT__WORD_HIGHLIGHTED,
    TEXT__SENTENCE_CLICK,
    TEXT__SENTENCE_READ,
    REVISION__CLICKED,
    REVISION__NOT_CLICKED,
    VIDEO__WAS_SEEN,
    VIDEO__TRANSLATION_WAS_REVEALED,
    BOOK_DRILL_CLICK,
    BOOK_DRILL_SCROLL
]

