export const USE_LINGUEE_SERVICES = true;

export const MINIMUM_LEMMAS_LEFT_FOR_SMART_FETCH_RELOAD = 5
export const LEMMAS_TO_FETCH_ON_SMART_FETCH = 30

export const EVENT_TYPES = {
    REVISION__CLICKED: "REVISION__CLICKED",
    REVISION__NOT_CLICKED: "REVISION__NOT_CLICKED",
    BOOK_DRILL_SCROLL: "BOOK_DRILL_SCROLL",
    BOOK_DRILL_CLICK: "BOOK_DRILL_CLICK"
}