from mq.signals import StopLearningLemmaEvent, LemmaShouldBeLearntEvent
from api.data_interpretation._etl import on_stop_learning_remove_datapoint_from_datapoint_collection
from api.data_interpretation._caching import \
    on_lemma_should_be_learnt_cache_examples_and_frequency


LemmaShouldBeLearntEvent.addEventListener(
    on_lemma_should_be_learnt_cache_examples_and_frequency)

StopLearningLemmaEvent.addEventListener(
    on_stop_learning_remove_datapoint_from_datapoint_collection)
